name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint isort black pytest

      - name: Run pylint
        run: pylint cache_simulator

      - name: Run isort (check only)
        run: isort cache_simulator --check --diff

      - name: Run black (check only)
        run: black cache_simulator --check

      - name: Run pytest
        run: python -m pytest tests
