name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. Clone the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # 3. Install Poetry
      - name: Install Poetry
        run: python -m pip install poetry==2.1.3 --no-cache-dir

      # 4. Install project dependencies, excluding the "special" group
      - name: Install dependencies
        run: poetry install --without special --with dev

      # 5. Update git tag and changelog
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run semantic-release publish --debug
